name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish (no MSIX, just EXE)
        run: dotnet publish SecretKey.UI/SecretKey.UI.csproj -c Release -r win-x64 --self-contained false -o publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SecretKey-build
          path: publish
